"""Add surat_template table

Revision ID: 057497f46b0a
Revises: c8f1e2d3a4b5
Create Date: 2026-05-26 06:59:31.186894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '057497f46b0a'
down_revision: Union[str, None] = 'c8f1e2d3a4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surat_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jenis', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surat_templates_id'), 'surat_templates', ['id'], unique=False)
    op.create_index(op.f('ix_surat_templates_jenis'), 'surat_templates', ['jenis'], unique=True)
    op.drop_index(op.f('ix_letter_templates_id'), table_name='letter_templates')
    op.drop_table('letter_templates')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('letter_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('template_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('required_fields', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('letter_templates_pkey')),
    sa.UniqueConstraint('name', name=op.f('letter_templates_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_letter_templates_id'), 'letter_templates', ['id'], unique=False)
    op.drop_index(op.f('ix_surat_templates_jenis'), table_name='surat_templates')
    op.drop_index(op.f('ix_surat_templates_id'), table_name='surat_templates')
    op.drop_table('surat_templates')
    # ### end Alembic commands ###
